name: Release
on:
  push:
    tags: ["*"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: riji.exe
          path: target/release/riji.exe

  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: riji
          path: target/release/riji

  create-release:
    needs: [windows, linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: riji.exe
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: riji

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            riji.exe
            riji
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
