name: Release
on:
  push:
    tags: ["*"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: riji.exe
          path: target/release/riji.exe

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: riji
          path: target/release/riji

  create-release:
    needs: [windows, linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: riji.exe
          path: ./riji.exe
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: riji
          path: ./riji

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Upload Release Asset
        id: upload-release-asset-windows 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./riji.exe
          asset_name: riji.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset
        id: upload-release-asset-linux 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./riji
          asset_name: riji
          asset_content_type: application/octet-stream
